spring:
  application:
    name: online-course-auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/auth-service
    username: root
    password: 123456
  jpa:
    hibernate.ddl-auto: update
    open-in-view: true
    show-sql: true

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security.web.access: DEBUG