server:
  port: 8081

spring:
  application:
    name: online-course-eureka-server
  # cloud:
  #   discovery:
  #     enabled: false

eureka:
  # instance:
  #   hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
    fetch-registry: false
    register-with-eureka: false
